name: Manual Terraform Azure Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      TF_VAR_postgres_admin_username: ${{ secrets.POSTGRES_ADMIN_USERNAME }}
      TF_VAR_postgres_admin_password: ${{ secrets.POSTGRES_ADMIN_PASSWORD }}

      TF_STATE_RESOURCE_GROUP: terraform-state-rg
      TF_STATE_STORAGE_ACCOUNT: tfstatearen007
      TF_STATE_CONTAINER: tfstate
      LOCATION: centralus

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get GitHub runner public IP
        run: |
          RUNNER_IP=$(curl -s https://api.ipify.org)
          echo "GitHub runner public IP: $RUNNER_IP"
          echo "TF_VAR_client_ip_address=$RUNNER_IP" >> $GITHUB_ENV

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Terraform state resource group
        run: |
          az group create \
            --name "$TF_STATE_RESOURCE_GROUP" \
            --location "$LOCATION"

      - name: Create Terraform state storage account
        run: |
          if ! az storage account show \
            --name "$TF_STATE_STORAGE_ACCOUNT" \
            --resource-group "$TF_STATE_RESOURCE_GROUP" \
            --query name \
            -o tsv >/dev/null 2>&1; then

            az storage account create \
              --name "$TF_STATE_STORAGE_ACCOUNT" \
              --resource-group "$TF_STATE_RESOURCE_GROUP" \
              --location "$LOCATION" \
              --sku Standard_LRS \
              --kind StorageV2 \
              --allow-blob-public-access false
          else
            echo "Terraform state storage account already exists."
          fi

      

      - name: Create Terraform state container
        run: |
         ACCOUNT_KEY=$(az storage account keys list \
         --resource-group "$TF_STATE_RESOURCE_GROUP" \
         --account-name "$TF_STATE_STORAGE_ACCOUNT" \
         --query '[0].value' \
         -o tsv)

         echo "ARM_ACCESS_KEY=$ACCOUNT_KEY" >> $GITHUB_ENV

         az storage container create \
          --name "$TF_STATE_CONTAINER" \
          --account-name "$TF_STATE_STORAGE_ACCOUNT" \
          --account-key "$ACCOUNT_KEY"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Configure Function App database environment variables
        working-directory: terraform
        env:
          DB_USER: ${{ secrets.POSTGRES_ADMIN_USERNAME }}
          DB_PASSWORD: ${{ secrets.POSTGRES_ADMIN_PASSWORD }}
        run: |
          DB_HOST=$(terraform output -raw postgresql_server_fqdn)

          az functionapp config appsettings set \
            --resource-group sampleblogapp01 \
            --name myblogappazure007 \
            --settings \
              DB_HOST="$DB_HOST" \
              DB_PORT="5432" \
              DB_NAME="posts" \
              DB_USER="$DB_USER" \
              DB_PASSWORD="$DB_PASSWORD" \
              DB_SSL="true"  
        
      - name: Configure Function App CORS
        working-directory: terraform
        run: |
         WEBSITE_URL=$(terraform output -raw website_url)

         echo "Adding CORS origin: $WEBSITE_URL"

         az functionapp cors add \
         --resource-group sampleblogapp01 \
         --name myblogappazure007 \
         --allowed-origins "$WEBSITE_URL"

      
      - name: Replace API URL in index.html
        working-directory: terraform
        run: |
          API_URL=$(terraform output -raw function_app_url)

          echo "Using API URL: $API_URL"

          cp ../index.html ./index.html
          sed -i "s|__API_URL__|$API_URL|g" ./index.html

      - name: Upload index.html to Azure Storage static website
        working-directory: terraform
        run: |
          STORAGE_CONNECTION_STRING=$(terraform output -raw storage_connection_string)

          az storage blob upload \
            --container-name '$web' \
            --name index.html \
            --file ./index.html \
            --connection-string "$STORAGE_CONNECTION_STRING" \
            --overwrite true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Function App dependencies
        working-directory: functions-app
        run: npm ci

      - name: Build Function App
        working-directory: functions-app
        run: npm run build --if-present

      - name: Deploy Node app to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: myblogappazure007
          package: functions-app      

      - name: Show website URL
        working-directory: terraform
        run: |
          echo "Website URL:"
          terraform output -raw website_url
