name: Manual Terraform Azure Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      TF_VAR_postgres_admin_username: ${{ secrets.POSTGRES_ADMIN_USERNAME }}
      TF_VAR_postgres_admin_password: ${{ secrets.POSTGRES_ADMIN_PASSWORD }}

      TF_STATE_RESOURCE_GROUP: terraform-state-rg
      TF_STATE_STORAGE_ACCOUNT: tfstatearen007
      TF_STATE_CONTAINER: tfstate
      LOCATION: centralus

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get GitHub runner public IP
        run: |
          RUNNER_IP=$(curl -s https://api.ipify.org)
          echo "GitHub runner public IP: $RUNNER_IP"
          echo "TF_VAR_client_ip_address=$RUNNER_IP" >> $GITHUB_ENV

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Terraform state resource group
        run: |
          az group create \
            --name "$TF_STATE_RESOURCE_GROUP" \
            --location "$LOCATION"

      - name: Create Terraform state storage account
        run: |
          if ! az storage account show \
            --name "$TF_STATE_STORAGE_ACCOUNT" \
            --resource-group "$TF_STATE_RESOURCE_GROUP" \
            --query name \
            -o tsv >/dev/null 2>&1; then

            az storage account create \
              --name "$TF_STATE_STORAGE_ACCOUNT" \
              --resource-group "$TF_STATE_RESOURCE_GROUP" \
              --location "$LOCATION" \
              --sku Standard_LRS \
              --kind StorageV2 \
              --allow-blob-public-access false
          else
            echo "Terraform state storage account already exists."
          fi

      - name: Grant Terraform state blob access
        run: |
          az role assignment create \
            --assignee "${{ secrets.AZURE_CLIENT_ID }}" \
            --role "Storage Blob Data Contributor" \
            --scope "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/$TF_STATE_RESOURCE_GROUP/providers/Microsoft.Storage/storageAccounts/$TF_STATE_STORAGE_ACCOUNT" \
            || true

      - name: Wait for role assignment propagation
        run: sleep 60

      - name: Create Terraform state container
        run: |
          az storage container create \
            --name "$TF_STATE_CONTAINER" \
            --account-name "$TF_STATE_STORAGE_ACCOUNT" \
            --auth-mode login

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Replace API URL in index.html
        working-directory: terraform
        run: |
          API_URL=$(terraform output -raw function_app_url)

          echo "Using API URL: $API_URL"

          cp ../index.html ./index.html
          sed -i "s|__API_URL__|$API_URL|g" ./index.html

      - name: Upload index.html to Azure Storage static website
        working-directory: terraform
        run: |
          STORAGE_CONNECTION_STRING=$(terraform output -raw storage_connection_string)

          az storage blob upload \
            --container-name '$web' \
            --name index.html \
            --file ./index.html \
            --connection-string "$STORAGE_CONNECTION_STRING" \
            --overwrite true

      - name: Show website URL
        working-directory: terraform
        run: |
          echo "Website URL:"
          terraform output -raw website_url
